### ISSUE TITLE
Failing to launch the code

### ISSUE THREAD

**Issue by ghost** [esgn/pva-ign#1]
Dear contributor
Many thanks for your excellent script that answers exactly to my request. Unfortunately, when I tried to launch the code, I get the following error:

**_File "/usr/lib/python3.8/curses/__init__.py", line 111, in wrapper
    nocbreak()

error: nocbreak() returned ERR_**

Do you have an idea of the problem?

Below my configuration:

Ubuntu 20.04
IDE: Spyder 3
Python 3.8.5

Best regards

**Comment by ghost** [comment]
Dear Emmanuel
Finally, the script works very well when I comment the code block dealing with the pick library.
Did the script select only the images from the campaign that intersect the bounding box, or all images for a given campaign for which at least only one image of the campaign intersects the bounding box?
Thank you for your answer.
Best regards

**Comment by esgn** [comment]
Added an option that demonstrates how to get aerial images that intersects the bounding box.
